server:
  tomcat:
    threads:
      max: 1

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul
    username: srpark
    password: '!@#QWE123qwe'