server:
  tomcat:
    threads:
      max: 1

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:13306/study?serverTimezone=Asia/Seoul
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 10
      validation-timeout: 5000
      connection-init-sql: SELECT 1